profile: "${PROFILE}"
lcp:
  host: "${LCP_HOST}"
  port: ${LCP_PORT}
  public_base_url: "${LCP_BASE_URL}"
  database: "${DB_URI}"
  auth_file: "${AUTH_FILE}"
  readonly: ${READONLY_BOOL}

certificate:
  cert: "${CERTIFICATE_PATH}"
  private_key: "${PRIVATE_KEY}"

lsd:
  public_base_url: "${LSD_BASE_URL}"
lsd_notify_auth: 
  username: "${LSD_NOTIFY_AUTH_USER}"
  password: "${LSD_NOTIFY_AUTH_PASS}"

storage:
  mode: "s3" # be carefull need upercase
  endpoint: "${S3_ENDPOINTS}"
  access_id: "${S3_ACCESS_ID}"
  disable_ssl: ${S3_DISABLE_SSL_BOOL}
  secret: "${S3_SECRET}"
  bucket: "${S3_BUCKET}"
  region: "${S3_REGION}"
  token: "${S3_TOKEN}"
  pathStyle: true

localization:
  languages: ${LOCALIZATION_LANGUAGES_ARRAY} # ["en-US"]
  folder: "${LOCALIZATION_FOLDER}"  # /src/github.com/readium/readium-lcp-server/messages/
  default_language: "${LOCALIZATION_DEFAULT_LANGUAGE}" # "en-US"

aes256_cbc_or_gcm: "${AES256}" # "_GCM"
